version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "5000:80"
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
    depends_on:
      - first
      - second

  first:
    build:
      context: .
    image: test_server
    container_name: first_server
    expose:
      - "8080"
    environment:
      TEST_NAME: first

  second:
    image: test_server
    container_name: second_server
    expose:
      - "8080"
    environment:
      TEST_NAME: second
